name: toc_trade_protobuf
description: "Pre-compiled protobuf for dart"
version: "0.1.9"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0

homepage: https://tocandraw.com/about-trade-agent/

platforms:
  android:
  ios:
